### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by SamKTaylor** [battlecode/battlecode20-scaffold#10]
Running matches with my bot works fine through the visualiser but trying to run them through Intellij results in the following error:

```
Exception in thread "ourBot.RobotPlayer #0" java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at battlecode.instrumenter.TeamClassLoaderFactory.normalReader(TeamClassLoaderFactory.java:233)
	at battlecode.instrumenter.bytecode.MethodCostUtil.getMethodData(MethodCostUtil.java:96)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.getMethodData(InstrumentingMethodVisitor.java:668)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMethodInsnNode(InstrumentingMethodVisitor.java:406)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMaxs(InstrumentingMethodVisitor.java:120)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at battlecode.instrumenter.TeamClassLoaderFactory$Loader.instrument(TeamClassLoaderFactory.java:527)
	at battlecode.instrumenter.TeamClassLoaderFactory$Loader.loadClass(TeamClassLoaderFactory.java:448)
	at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:238)
	at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "ourBot.RobotPlayer #1" java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at battlecode.instrumenter.TeamClassLoaderFactory.normalReader(TeamClassLoaderFactory.java:233)
	at battlecode.instrumenter.bytecode.MethodCostUtil.getMethodData(MethodCostUtil.java:96)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.getMethodData(InstrumentingMethodVisitor.java:668)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMethodInsnNode(InstrumentingMethodVisitor.java:406)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMaxs(InstrumentingMethodVisitor.java:120)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at battlecode.instrumenter.TeamClassLoaderFactory$Loader.instrument(TeamClassLoaderFactory.java:527)
	at battlecode.instrumenter.TeamClassLoaderFactory$Loader.loadClass(TeamClassLoaderFactory.java:448)
	at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:238)
	at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by arvid220u** [comment]
Did you try https://2020.battlecode.org/common-issues? It seems like the client is unable to find the correct JDK version.
