### ISSUE TITLE
Can't run the bot on Mac OS X

### ISSUE THREAD

**Issue by Tolsi** [battlecode/battlecode20-scaffold#6]
When I start a game using the runner from BC client v2020.1.0.2 on Mac OS X with a default bot realization, then I got that error:  

```> Task :compileJava


> Task :processResources NO-SOURCE
> Task :classes
> Task :jar
> Task :assemble

> Task :compileTestJava

UP-TO-DATE

> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE

> Task :test

> Task :check
> Task :unpackClient32 SKIPPED
> Task :build



> Task :runFromClient
Waiting for connection from client...
Connection received!
[server] -------------------- Match Starting --------------------
[server] examplefuncsplayer vs. lectureplayer on CentralSoup

Exception in thread "examplefuncsplayer.RobotPlayer #0" java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.(Unknown Source)
at org.objectweb.asm.ClassReader.(Unknown Source)
at org.objectweb.asm.ClassReader.(Unknown Source)
at battlecode.instrumenter.TeamClassLoaderFactory.normalReader(TeamClassLoaderFactory.java:233)
at battlecode.instrumenter.bytecode.MethodCostUtil.getMethodData(MethodCostUtil.java:96)

at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.getMethodData(InstrumentingMethodVisitor.java:668)
at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMethodInsnNode(InstrumentingMethodVisitor.java:406)
at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMaxs(InstrumentingMethodVisitor.java:120)
at org.objectweb.asm.ClassReader.a(Unknown Source)
at org.objectweb.asm.ClassReader.b(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)

at battlecode.instrumenter.TeamClassLoaderFactory$Loader.instrument(TeamClassLoaderFactory.java:527)
at battlecode.instrumenter.TeamClassLoaderFactory$Loader.loadClass(TeamClassLoaderFactory.java:448)
at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:238)
at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "lectureplayer.RobotPlayer #1" java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.(Unknown Source)
at org.objectweb.asm.ClassReader.(Unknown Source)
at org.objectweb.asm.ClassReader.(Unknown Source)
at battlecode.instrumenter.TeamClassLoaderFactory.normalReader(TeamClassLoaderFactory.java:233)
at battlecode.instrumenter.bytecode.MethodCostUtil.getMethodData(MethodCostUtil.java:96)
at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.getMethodData(InstrumentingMethodVisitor.java:668)
at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMethodInsnNode(InstrumentingMethodVisitor.java:406)
at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMaxs(InstrumentingMethodVisitor.java:120)

at org.objectweb.asm.ClassReader.a(Unknown Source)
at org.objectweb.asm.ClassReader.b(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)
at battlecode.instrumenter.TeamClassLoaderFactory$Loader.instrument(TeamClassLoaderFactory.java:527)
at battlecode.instrumenter.TeamClassLoaderFactory$Loader.loadClass(TeamClassLoaderFactory.java:448)
at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:238)
at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
at java.base/java.lang.Thread.run(Thread.java:830)

[server] nobody wins (round 1)
[server] Reason: The winning team won arbitrarily (highest robot ID).
[server] -------------------- Match Finished --------------------
[server:warning] Team NEUTRAL won???
Closed: /0:0:0:0:0:0:0:1:51333 for


BUILD SUCCESSFUL

in 6s
5 actionable tasks: 4 executed, 1 up-to-date
```

**Comment by Tolsi** [comment]
I tried to use it with OpenJDK 13 and switching to OpenJDK 1.8 helped me.
